CREATE TABLE SOLICITUDES 
(
  ID NUMBER NOT NULL 
, FILENAME VARCHAR2(32000) NOT NULL 
, EMAIL VARCHAR2(100) 
, RESPUESTA VARCHAR2(32000) 
, CREATED_DT TIMESTAMP 
, UPDATED_DT TIMESTAMP 
, CONSTRAINT SOLICITUDES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);
